# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: More checks
on:
  workflow_dispatch:
  push:

jobs:
  checks:
    name: More checks well

    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
